version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 123
    ports:
      - "8080:8080"
  wordpress:
    depends_on:
      - db
    build: .
    ports:
      - "8000:8082"
    restart: always

    